"use server";

export async function getOccupations() {
  return [
    "Akademisyen/Öğretim Görevlisi",
    "Aşçı",
    "Asker (Er/Erbaş)",
    "Astsubay/Uzman (Mecburi Askeri Görev Hariç)",
    "Avcı",
    "Avukat/Hukuk Müşaviri",
    "Bankacı",
    "Bomba İmha Çalışanı",
    "BÜROKRAT",
    "Çağrı Merkezi Çalışanı",
    "Çalışan/Memur",
    "Çiftçi",
    "Dalgıç",
    "Danışman",
    "Denetçi/Müfettiş",
    "Diş Hekimi",
    "Doktor",
    "Dublör",
    "Eczacı",
    "Ekonomist/Finans Uzmanı",
    "Emekli",
    "Emlak Komisyoncusu/Galerici",
    "Ev Hanımı",
    "Garson/Hizmetli/Temizlik Görevlisi",
    "Gayrimenkul Gelir Sahibi/Rantiye",
    "Gazeteci",
    "Gemi Yükleme/Kurtarma Çalışanı",
    "Görevli",
    "Güvenlik Görevlisi",
    "Güvenlik Görevlisi - Yakın Koruma",
    "Hakim/Savcı",
    "Hemşire",
    "Hostes",
    "INFLUENCER/SOSYAL MEDYA PROFESYONELI",
    "İşçi",
    "İşçi - Gaz ve Isıtma",
    "İşçi - İnşaat/Gemi İnşaat",
    "İşsiz",
    "İtfaiyeci",
    "JANDARMA",
    "Kimyager/Biyolog",
    "Korucu",
    "Kuafor/Güzellik Uzmanı/Berber",
    "Kurye (Motorsiklet)",
    "Kuyumcu/Sarraf",
    "Laborant/Sağlık Memuru/Sağlık Teknisyeni",
    "M.Vekili/Bakan/Bld. Başkanı/Diplomat",
    "Maden ve Ocak Çalışanı",
    "Mali Müşavir",
    "Memur",
    "Mimar/İç Mimar/Mühendis",
    "Muhabir",
    "Muhasebeci/SMM",
    "Mühendis",
    "Müteahhit",
    "Noter",
    "Ögrenci",
    "Öğretmen/Eğitmen",
    "Patlayıcı Uzmanı",
    "Pazarlama/Satış Elemanı",
    "Pilot/Kaptan",
    "Polis (Çevik Kuvvet)",
    "Polis/Emniyet Mensubu",
    "Programcı/Yazılımcı/Analist",
    "PSIKOLOG",
    "Radyoaktif Ortam Çalışanı",
    "Reklam Ve Halkla İlişkiler",
    "SAGLIK GOREVLISI",
    "SANATÇI(AKTÖR/AKTRIS/TIYATROCU)",
    "SANATÇI(DIGER)",
    "SANATÇI(MÜZISYEN)",
    "SANATÇI(RESSAM)",
    "SANATÇI(YAZAR/SAIR)",
    "Sanayici",
    "Sekreter/Yönetici Asistanı",
    "Serbest Meslek (Satıcı)",
    "Serbest Meslek (Zanaatkar)",
    "Sigortacı",
    "SIYASI GÖREV SAHIBI",
    "Şoför",
    "Sporcu - Diğer",
    "Sporcu - Futbolcu",
    "Sporcu - Tehlikeli Sporlar",
    "SPORCU(BASKETBOLCU)",
    "SPORCU(DIGER BRANS)",
    "SPORCU(FUTBOLCU)",
    "SPORCU(TENIS)",
    "SPORCU(VOLEYBOLCU)",
    "Subay/General (Mecburi Askeri Görev Hariç)",
    "Tacir/Tüccar",
    "Tehlikeli Madde ile Çalışanlar",
    "Teknisyen",
    "Tekstilci",
    "Tıbbi Mümessil",
    "Tüpçü",
    "Turizmci/Rehber",
    "Veteriner",
    "Yeraltı İnşaat/Tamir Çalışanı",
    "Yönetici/İşletmeci",
    "Yüksek Isıda Çalışanlar",
    "Yüksek Yerlerde Çalışanlar",
    "Zabıta",
  ] as string[];
}
